"""Neutral tool cards shared across S5 task classes (no task-specific call-order binding)."""

from __future__ import annotations

from app.orchestrator.s5_task_tool_catalogs.types import AgentToolDefinition

SHARED_TOOL_CATALOG: dict[str, AgentToolDefinition] = {
    "search_mcp": AgentToolDefinition(
        name="search_mcp",
        summary="公开网页检索（攻略、游记、季节、临时通知线索）。",
        when_to_use=[
            "需要发现官方页面、游记、通知类 URL 作为后续 browser/official 读取入口",
            "季节、攻略、评价类软信息，尚无结构化证据",
        ],
        when_not_to_use=[
            "已需要精确公里/驾车时长——应优先 baidu_route_mcp",
            "已有官方 URL 待读取——用 official_page_reader_mcp / browser_mcp",
        ],
        parameters={"search_query": "检索词（含地名锚点）", "information_need": "检索目的 claim 类型"},
        satisfies_needs=["public_web_search", "seasonality", "review_summary", "travel_advice"],
    ),
    "official_source_discovery_mcp": AgentToolDefinition(
        name="official_source_discovery_mcp",
        summary="从已有搜索结果中识别政府/景区/票务官方来源候选。",
        when_to_use=["opening_hours、ticket_price、seasonal_operation_status 等硬事实", "search_mcp 之后"],
        when_not_to_use=["仅需路线距离/时长"],
        parameters={"prior_evidence": "已有 search 证据", "claim_type": "目标 claim"},
        prerequisites=["search_mcp 或 keyword_search 已有 hits"],
        satisfies_needs=["opening_hours", "ticket_price", "seasonal_operation_status"],
        call_order_hint="通常在 search_mcp 之后、official_page_reader 之前",
    ),
    "official_page_reader_mcp": AgentToolDefinition(
        name="official_page_reader_mcp",
        summary="读取官方/政务/景区页面正文，提取开放时间与票价。",
        when_to_use=["需要核实官网上的开放时间、票价、预约政策"],
        when_not_to_use=["路线规划、两地距离"],
        parameters={"url": "官方页 URL（可选）", "place_name": "地点", "information_need": "opening_hours|ticket_price"},
        prerequisites=["official_source_discovery_mcp 或 search_mcp 提供 URL"],
        satisfies_needs=["opening_hours", "ticket_price", "reservation_policy"],
    ),
    "browser_mcp": AgentToolDefinition(
        name="browser_mcp",
        summary="动态网页抓取（非结构化官方页/公告）。",
        when_to_use=["official_page_reader 失败或需二次抓取公告页"],
        when_not_to_use=["两地驾车距离/时长"],
        satisfies_needs=["opening_hours", "temporary_closure", "travel_advice"],
    ),
    "baidu_place_search_mcp": AgentToolDefinition(
        name="baidu_place_search_mcp",
        summary="百度地图 POI 检索：解析景区正式名称、行政区、uid；周边圆形检索。",
        when_to_use=[
            "地点消歧（同名景区）",
            "路线规划前确认目的地 POI",
            "需要城市/区县上下文",
            "按坐标做周边 POI 圆形检索",
        ],
        when_not_to_use=["仅需要网页攻略文本"],
        parameters={
            "place_name": "景区/地点名",
            "city": "城市",
            "region": "行政区（消歧）",
            "tag": "POI 类型偏好，如美食/酒店/景点",
            "location": "圆形检索中心 lat,lng",
            "radius": "周边检索半径（米）",
            "anchor_location_key": "消歧候选 location_key（写入 evidence 归属）",
            "country": "China",
        },
        satisfies_needs=["entity_resolution", "place_lookup", "geo_resolution", "nearby_food", "nearby_poi"],
    ),
    "baidu_place_detail_mcp": AgentToolDefinition(
        name="baidu_place_detail_mcp",
        summary="百度地图 POI 详情（地址、评分、营业时间候选）。",
        when_to_use=["需要 POI 地址、候选营业时间、百度侧评分/人均"],
        when_not_to_use=["跨省驾车距离——用 baidu_route_mcp"],
        parameters={"uid": "来自 baidu_place_search_mcp 的 POI uid", "place_name": "地点名"},
        prerequisites=["baidu_place_search_mcp 提供 uid"],
        satisfies_needs=["opening_hours_candidate", "address_lookup", "rating_candidate"],
    ),
    "baidu_geocode_mcp": AgentToolDefinition(
        name="baidu_geocode_mcp",
        summary="地址/地名 → 经纬度坐标。",
        when_to_use=["天气/路线工具需要坐标但 evidence 中尚无"],
        parameters={"address": "地址或地名", "place_name": "地点"},
        satisfies_needs=["geocode", "coordinates"],
    ),
    "baidu_route_mcp": AgentToolDefinition(
        name="baidu_route_mcp",
        summary="百度地图两点路线规划：驾车/步行/公交距离与预计时长（结构化）。",
        when_to_use=[
            "用户问一日游是否够用、往返是否来得及——必须先算路程+驾车时长",
            "需要乌鲁木齐/阿勒泰等城市到景区的真实公里数（勿仅用攻略摘要）",
            "对比两地交通方式或评估 itinerary_feasibility",
            "问题含「多远」「多久」「怎么去」「一天够吗」且涉及城际交通",
        ],
        when_not_to_use=[
            "仅问景区内步行强度、游玩时长（无城际交通）",
            "仅问门票价格或开放时间",
        ],
        parameters={
            "origin": "起点城市/地点（必填；由 tool_parameters 或用户上下文提供）",
            "destination": "终点景区 POI 名（必填）",
            "mode": "driving|walking|transit，默认 driving",
            "place_name": "目的地景区名",
        },
        prerequisites=[
            "建议先 baidu_place_search_mcp 解析 destination",
            "origin/destination 必须同时提供",
        ],
        satisfies_needs=[
            "route_plan",
            "distance",
            "duration",
            "transport_planning",
            "itinerary_feasibility",
            "transit",
        ],
        call_order_hint="一日游/够玩吗类问题：在 search_mcp 之后、finish 之前必须尝试一次",
    ),
    "baidu_route_matrix_mcp": AgentToolDefinition(
        name="baidu_route_matrix_mcp",
        summary="百度地图多点距离/时间矩阵（多景点串联可行性）。",
        when_to_use=["多景点行程串联、比较多个目的地间车程", "comparison 模式两地交通对比"],
        when_not_to_use=["单点开放时间查询"],
        parameters={
            "origins": "起点列表",
            "destinations": "终点列表",
            "mode": "driving",
        },
        prerequisites=["baidu_place_search_mcp 解析各地点"],
        satisfies_needs=["route_plan", "itinerary_feasibility", "distance", "duration"],
    ),
    "baidu_traffic_mcp": AgentToolDefinition(
        name="baidu_traffic_mcp",
        summary="百度地图路况（拥堵、封路风险）。",
        when_to_use=["自驾路线风险、独库公路等路况", "已有路线或道路名"],
        when_not_to_use=["首次获取两地距离——先用 baidu_route_mcp"],
        parameters={"road_name": "道路名", "query": "路况查询词"},
        satisfies_needs=["traffic_status", "road_traffic", "congestion_risk"],
    ),
    "baidu_weather_mcp": AgentToolDefinition(
        name="baidu_weather_mcp",
        summary="百度地图天气（实时/短期预报）。",
        when_to_use=["今日天气、出行当日天气风险"],
        satisfies_needs=["weather_today", "forecast", "weather"],
    ),
    "keyword_search_agent": AgentToolDefinition(
        name="keyword_search_agent",
        summary="[legacy] 同 fact_search_agent — 网页/官方检索。",
        when_to_use=["向后兼容；优先使用 fact_search_agent"],
        when_not_to_use=["地点锚定、路线规划"],
        parameters={
            "lookup_intent": "需获取的证据描述",
            "claim_target": "目标 claim 类型",
            "tool_parameters": "结构化 MCP 参数",
        },
    ),
    "entity_resolution_agent": AgentToolDefinition(
        name="entity_resolution_agent",
        summary="S5 子代理：地点/POI 锚定与同名消歧。",
        when_to_use=["地点未解析", "place_candidates 歧义", "nearby 问题需先锚定地理上下文"],
        parameters={
            "lookup_intent": "锚定意图",
            "search_query": "地点名",
            "anchor_keywords": "地点 token",
            "tool_parameters": "region/city 等",
        },
        satisfies_needs=["entity_resolution", "geo_resolution", "place_lookup"],
    ),
    "nearby_anchor_strategy_agent": AgentToolDefinition(
        name="nearby_anchor_strategy_agent",
        summary="S5 子代理：判断周边检索用精确门点、模糊区域，或为每个消歧候选分别检索。",
        when_to_use=[
            "用户问「XX附近有什么」且地点可能歧义",
            "需确定检索中心坐标与半径",
            "同景区多门点/停车场并存",
        ],
        when_not_to_use=["纯城际路线距离问题", "门票硬事实无地理锚点"],
        parameters={
            "nearby_claim": "nearby_food|nearby_poi|…",
            "candidates": "place_candidates 列表（可选）",
            "parent_subagent": "调用方子代理名",
        },
        satisfies_needs=["nearby_food", "nearby_poi", "restaurant_recommendation"],
    ),
    "call_subagent": AgentToolDefinition(
        name="call_subagent",
        summary="S5 子代理递归委托：在当前子代理内调用另一个子代理。",
        when_to_use=["需专项子代理补证或锚点策略"],
        when_not_to_use=["已有等价 MCP 工具可直接调用时"],
        parameters={
            "target_subagent": "nearby_anchor_strategy_agent|fact_search_agent|…",
            "arguments": "子代理 task 字段",
        },
    ),
    "dianping_nearby_crawler_mcp": AgentToolDefinition(
        name="dianping_nearby_crawler_mcp",
        summary="大众点评附近商户：按评分、评论量、星级筛选餐厅/酒店候选。",
        when_to_use=[
            "需筛选评价好、评论多、星级高的店铺",
            "已确定检索锚点（门点/景区中心坐标）",
        ],
        when_not_to_use=["无城市/地点锚点", "非餐饮类硬事实"],
        parameters={
            "place_name": "锚点景区或门点名称",
            "city": "城市",
            "query": "检索词（如 美食 餐厅）",
            "mode": "nearby_search",
            "sort_by": "rating_review_count",
        },
        prerequisites=["entity_resolution 或 nearby_anchor_strategy 已给出锚点"],
        satisfies_needs=["nearby_food", "restaurant_recommendation", "rating_candidate", "review_summary"],
    ),
    "dianping_review_crawler_mcp": AgentToolDefinition(
        name="dianping_review_crawler_mcp",
        summary="大众点评店铺评价与评分：验证口碑、避雷、人均消费线索。",
        when_to_use=[
            "已有餐厅名称需核实评分/评论摘要",
            "对比多家候选餐厅口碑",
        ],
        when_not_to_use=["仅要 POI 坐标消歧"],
        parameters={"place_name": "店名或景区", "city": "城市", "query": "店名+美食"},
        satisfies_needs=["review_summary", "rating_candidate", "value_for_money", "nearby_food"],
    ),
    "route_feasibility_agent": AgentToolDefinition(
        name="route_feasibility_agent",
        summary="S5 子代理：距离/时长/路况（内部调用百度 route MCP）。",
        when_to_use=["一日游够玩吗", "多远多久", "自驾路况"],
        parameters={
            "tool_parameters": "origin, destination, mode, road_name",
            "lookup_intent": "路线检索意图",
        },
        satisfies_needs=["route_plan", "distance", "duration", "itinerary_feasibility"],
    ),
    "fact_search_agent": AgentToolDefinition(
        name="fact_search_agent",
        summary="S5 子代理：网页/官方/票务硬事实检索（search_mcp 等）。",
        when_to_use=["门票、开放时间、海拔、攻略事实"],
        parameters={
            "lookup_intent": "证据目标描述",
            "search_query": "检索词组",
            "anchor_keywords": "锚定关键词",
            "claim_target": "claim 类型",
        },
        satisfies_needs=["ticket_price", "opening_hours", "elevation", "general_fact"],
    ),
    "weather_context_agent": AgentToolDefinition(
        name="weather_context_agent",
        summary="S5 子代理：短期天气/气候 MCP。",
        when_to_use=["今日/明日天气"],
        satisfies_needs=["forecast", "weather", "weather_today"],
    ),
    "search_task_planner_agent": AgentToolDefinition(
        name="search_task_planner_agent",
        summary="S5 子代理：将用户问题分解为 keyword_search 任务。",
        when_to_use=["S5 开始时规划检索词", "每 2 次 keyword_search 后 refine"],
        parameters={"refine": "true 表示基于已有 evidence 调整检索"},
    ),
}
