"""Policy-level MCP tool names, server bindings, and capabilities."""

from __future__ import annotations

# policy_tool_name -> (server_key, default_mcp_tool_name, capabilities)
MCP_POLICY_SPECS: dict[str, tuple[str, str, list[str]]] = {
    "search_mcp": (
        "search",
        "public_web_search",
        [
            "public_web_search",
            "official_page_discovery",
            "tourism_board_search",
            "seasonality_search",
            "event_search",
            "temporary_notice_search",
        ],
    ),
    "browser_mcp": (
        "browser",
        "dynamic_page_read",
        [
            "official_page_read",
            "tourism_board_page_read",
            "dynamic_page_read",
            "html_extract",
            "notice_page_read",
        ],
    ),
    "official_page_reader_mcp": (
        "search",
        "fetch-web",
        [
            "official_page_read",
            "tourism_board_page_read",
            "html_extract",
            "notice_page_read",
        ],
    ),
    "official_source_discovery_mcp": (
        "local",
        "official_source_discovery",
        [
            "official_source_classification",
            "search_hit_normalization",
            "official_source_candidate",
        ],
    ),
    "osm_mcp": (
        "osm",
        "place_lookup",
        ["geocode", "place_lookup", "coordinates", "country_region_lookup", "nearby_poi", "route_proxy"],
    ),
    "places_mcp": (
        "osm",
        "place_lookup",
        ["geocode", "place_lookup", "coordinates", "nearby_poi", "route_proxy"],
    ),
    "geocode_mcp": (
        "osm",
        "geocode",
        ["geocode", "coordinates", "country_region_lookup"],
    ),
    "openmeteo_mcp": (
        "openmeteo",
        "forecast",
        [
            "current_weather",
            "forecast",
            "historical_weather",
            "monthly_climate",
            "precipitation_probability",
            "temperature_range",
            "weather_risk",
        ],
    ),
    "weather_mcp": (
        "openmeteo",
        "current_weather",
        ["current_weather", "forecast", "weather_risk"],
    ),
    "climate_mcp": (
        "openmeteo",
        "monthly_climate",
        ["monthly_climate", "historical_weather", "temperature_range", "precipitation_probability"],
    ),
    "wikipedia_mcp": (
        "wikipedia",
        "destination_overview",
        ["destination_overview", "attraction_background", "entity_description", "multilingual_alias"],
    ),
    "wikidata_mcp": (
        "wikidata",
        "entity_resolution",
        [
            "entity_resolution",
            "alias_lookup",
            "coordinates",
            "country_region_lookup",
            "instance_of",
            "administrative_area",
        ],
    ),
    "sqlite_mcp": (
        "sqlite",
        "read_evidence_cache",
        ["read_evidence_cache", "read_place_cache", "query_tool_trace"],
    ),
    "evidence_store_mcp": (
        "sqlite",
        "read_evidence_cache",
        ["read_evidence_cache", "read_place_cache", "query_tool_trace"],
    ),
    "baidu_place_search_mcp": (
        "baidu_map",
        "map_search_places",
        [
            "entity_resolution",
            "place_lookup",
            "poi_search",
            "country_region_lookup",
            "city_region_lookup",
        ],
    ),
    "baidu_place_detail_mcp": (
        "baidu_map",
        "map_place_details",
        [
            "place_details",
            "address_lookup",
            "opening_hours_candidate",
            "rating_candidate",
            "price_candidate",
            "uid_detail_lookup",
        ],
    ),
    "baidu_weather_mcp": (
        "baidu_map",
        "map_weather",
        ["current_weather", "forecast", "weather_risk", "short_term_weather"],
    ),
    "baidu_geocode_mcp": (
        "baidu_map",
        "map_geocode",
        [
            "geocode",
            "address_to_coordinates",
            "city_region_lookup",
            "coordinate_resolution",
        ],
    ),
    "baidu_reverse_geocode_mcp": (
        "baidu_map",
        "map_reverse_geocode",
        [
            "reverse_geocode",
            "coordinates_to_address",
            "administrative_area_lookup",
            "nearby_context",
        ],
    ),
    "baidu_route_mcp": (
        "baidu_map",
        "map_directions",
        [
            "route_planning",
            "transport_planning",
            "driving_route",
            "walking_route",
            "transit_route",
            "cycling_route",
            "distance",
            "duration",
            "route_steps",
        ],
    ),
    "baidu_route_matrix_mcp": (
        "baidu_map",
        "map_directions_matrix",
        [
            "directions_matrix",
            "multi_origin_destination_distance",
            "travel_time_matrix",
            "itinerary_feasibility",
            "scenic_spot_ordering",
        ],
    ),
    "baidu_traffic_mcp": (
        "baidu_map",
        "map_road_traffic",
        [
            "road_traffic",
            "traffic_status",
            "congestion_risk",
            "self_drive_risk",
            "route_traffic_context",
        ],
    ),
    "baidu_ip_location_mcp": (
        "baidu_map",
        "map_ip_location",
        [
            "ip_location",
            "user_city_estimation",
            "user_coordinate_estimation",
        ],
    ),
}

# Ticket/review providers (non-MCP-server; registered via attach_ticket_providers)
TICKET_PROVIDER_SPECS: dict[str, tuple[str, str, list[str]]] = {
    "ticketlens_experience_mcp": (
        "ticketlens",
        "experience_search",
        [
            "ticket_price_candidate",
            "activity_price",
            "attraction_ticket_search",
            "experience_search",
            "booking_channel",
            "tour_search",
            "review_signal_candidate",
        ],
    ),
    "ticketlens_experience_review_signal_mcp": (
        "ticketlens",
        "review_signal",
        ["review_signal", "rating_candidate", "review_summary"],
    ),
    "ctrip_review_crawler_mcp": (
        "ctrip_crawler",
        "review_signal",
        [
            "review_signal",
            "attraction_review_summary",
            "value_for_money",
            "crowd_risk",
            "queue_risk",
            "ticket_related_mentions",
        ],
    ),
    "ctrip_ticket_signal_crawler_mcp": (
        "ctrip_crawler",
        "ticket_signal",
        ["ticket_related_mentions", "ticket_price_candidate"],
    ),
    "fliggy_ticket_snapshot_crawler_mcp": (
        "fliggy_crawler",
        "ticket_snapshot",
        [
            "ticket_price_candidate",
            "ticket_sales_signal",
            "booking_channel",
            "platform_ticket_url",
            "historical_ticket_snapshot",
        ],
    ),
    "fliggy_ticket_review_signal_mcp": (
        "fliggy_crawler",
        "review_signal",
        ["review_signal", "crowd_proxy"],
    ),
    "dianping_review_crawler_mcp": (
        "dianping_crawler",
        "review_signal",
        [
            "review_signal",
            "value_for_money",
            "crowd_risk",
            "queue_risk",
            "commercialization_risk",
            "ticket_related_mentions",
        ],
    ),
    "dianping_ticket_signal_crawler_mcp": (
        "dianping_crawler",
        "ticket_signal",
        ["ticket_related_mentions", "rating_candidate"],
    ),
    "ctrip_guide_crawler_mcp": (
        "ctrip_crawler",
        "travel_guide",
        ["seasonality", "best_time_to_visit", "scenery_by_month", "crowd_by_season"],
    ),
    "dianping_nearby_crawler_mcp": (
        "dianping_crawler",
        "nearby_poi",
        [
            "nearby_poi",
            "restaurant_candidate",
            "rating_candidate",
            "price_level_candidate",
        ],
    ),
    "crowd_estimation_mcp": (
        "crowd_estimation",
        "crowd_proxy",
        ["current_crowd_estimate", "queue_risk", "congestion_risk", "holiday_crowd_risk"],
    ),
    "ticket_snapshot_store": (
        "ticket_snapshot",
        "save_snapshot",
        ["historical_ticket_snapshot", "ticket_price_candidate"],
    ),
    "ticket_price_history_query": (
        "ticket_snapshot",
        "price_history",
        ["ticket_price_history", "historical_ticket_snapshot", "platform_price_difference"],
    ),
}
MCP_POLICY_SPECS.update(TICKET_PROVIDER_SPECS)

# S5 placeholder provider tools — domain registry only; no real adapter.
for _placeholder_name in (
    "fliggy_ticket_crawler_mcp",
    "meituan_ticket_crawler_mcp",
    "dianping_ticket_crawler_mcp",
    "qunar_ticket_crawler_mcp",
    "tourism_board_notice_mcp",
    "platform_notice_crawler_mcp",
    "mafengwo_note_crawler_mcp",
    "xiaohongshu_note_crawler_mcp",
    "review_signal_mcp",
    "public_review_search_mcp",
    "meituan_review_crawler_mcp",
    "qunar_review_crawler_mcp",
    "tripadvisor_review_crawler_mcp",
    "nearby_food_mcp",
    "nearby_rest_area_mcp",
    "nearby_toilet_mcp",
    "nearby_parking_mcp",
    "nearby_station_mcp",
    "nearby_attraction_mcp",
    "nearby_hotel_mcp",
    "meituan_nearby_crawler_mcp",
    "itinerary_planner_mcp",
    "route_feasibility_checker_mcp",
    "elderly_friendly_route_scorer_mcp",
    "family_trip_planner_mcp",
    "event_calendar_mcp",
):
    MCP_POLICY_SPECS[_placeholder_name] = (
        "placeholder",
        _placeholder_name,
        ["placeholder_provider"],
    )

MCP_POLICY_TOOL_NAMES = frozenset(MCP_POLICY_SPECS.keys())

# Legacy registry attribute aliases (policy name may differ from registry attr)
POLICY_TO_REGISTRY_ATTR: dict[str, str] = {
    "search_mcp": "search_mcp",
    "browser_mcp": "browser_mcp",
    "official_page_reader_mcp": "official_page_reader_mcp",
    "official_mcp": "official_page_reader_mcp",
    "official_source_discovery_mcp": "official_source_discovery_mcp",
    "osm_mcp": "osm_mcp",
    "places_mcp": "places_mcp",
    "geocode_mcp": "geocode_mcp",
    "openmeteo_mcp": "openmeteo_mcp",
    "weather_mcp": "weather_mcp",
    "climate_mcp": "climate_mcp",
    "wikipedia_mcp": "wikipedia_mcp",
    "wikidata_mcp": "wikidata_mcp",
    "sqlite_mcp": "sqlite_mcp",
    "evidence_store_mcp": "evidence_store_mcp",
    "baidu_place_search_mcp": "baidu_place_search_mcp",
    "baidu_place_detail_mcp": "baidu_place_detail_mcp",
    "baidu_weather_mcp": "baidu_weather_mcp",
    "baidu_geocode_mcp": "baidu_geocode_mcp",
    "baidu_reverse_geocode_mcp": "baidu_reverse_geocode_mcp",
    "baidu_route_mcp": "baidu_route_mcp",
    "baidu_route_matrix_mcp": "baidu_route_matrix_mcp",
    "baidu_traffic_mcp": "baidu_traffic_mcp",
    "baidu_ip_location_mcp": "baidu_ip_location_mcp",
    "ticketlens_experience_mcp": "ticketlens_experience_mcp",
    "ticketlens_experience_review_signal_mcp": "ticketlens_experience_review_signal_mcp",
    "ctrip_review_crawler_mcp": "ctrip_review_crawler_mcp",
    "ctrip_ticket_signal_crawler_mcp": "ctrip_ticket_signal_crawler_mcp",
    "fliggy_ticket_snapshot_crawler_mcp": "fliggy_ticket_snapshot_crawler_mcp",
    "fliggy_ticket_review_signal_mcp": "fliggy_ticket_review_signal_mcp",
    "dianping_review_crawler_mcp": "dianping_review_crawler_mcp",
    "dianping_ticket_signal_crawler_mcp": "dianping_ticket_signal_crawler_mcp",
    "ticket_snapshot_store": "ticket_snapshot_store",
    "ticket_price_history_query": "ticket_price_history_query",
    # backward compat
    "mcp_weather": "weather_mcp",
    "mcp_places": "places_mcp",
    "mcp_official": "official_page_reader_mcp",
}

NEED_TOOL_PROFILES: dict[str, list[str]] = {
    "best_time_to_visit": [
        "baidu_place_search_mcp",
        "baidu_place_detail_mcp",
        "baidu_geocode_mcp",
        "baidu_reverse_geocode_mcp",
        "search_mcp",
        "browser_mcp",
        "openmeteo_mcp",
        "climate_mcp",
        "wikipedia_mcp",
        "wikidata_mcp",
        "osm_mcp",
        "seasonality",
        "knowledge_prior",
        "fallback",
        "weather",
    ],
    "seasonality": [
        "baidu_place_search_mcp",
        "baidu_place_detail_mcp",
        "baidu_geocode_mcp",
        "baidu_reverse_geocode_mcp",
        "search_mcp",
        "browser_mcp",
        "openmeteo_mcp",
        "climate_mcp",
        "wikipedia_mcp",
        "wikidata_mcp",
        "osm_mcp",
        "seasonality",
        "knowledge_prior",
        "fallback",
    ],
    "climate_monthly": ["openmeteo_mcp", "climate_mcp", "weather", "weather_mcp"],
    "monthly_weather": ["openmeteo_mcp", "climate_mcp", "weather_mcp", "weather"],
    "opening_hours": [
        "search_mcp",
        "official_source_discovery_mcp",
        "official_page_reader_mcp",
        "browser_mcp",
        "baidu_place_search_mcp",
        "baidu_place_detail_mcp",
        "osm_mcp",
        "places_mcp",
        "places",
        "fallback",
    ],
    "temporary_closure": [
        "search_mcp",
        "official_source_discovery_mcp",
        "official_page_reader_mcp",
        "browser_mcp",
        "baidu_place_search_mcp",
        "baidu_place_detail_mcp",
        "places",
        "fallback",
    ],
    "reservation_policy": [
        "search_mcp",
        "official_source_discovery_mcp",
        "official_page_reader_mcp",
        "browser_mcp",
        "baidu_place_search_mcp",
        "baidu_place_detail_mcp",
        "fallback",
    ],
    "ticket_price": [
        "search_mcp",
        "official_source_discovery_mcp",
        "official_page_reader_mcp",
        "browser_mcp",
        "baidu_place_search_mcp",
        "baidu_place_detail_mcp",
        "baidu_geocode_mcp",
        "ticketlens_experience_mcp",
        "ctrip_ticket_signal_crawler_mcp",
        "fliggy_ticket_snapshot_crawler_mcp",
        "dianping_ticket_signal_crawler_mcp",
        "ticket_snapshot_store",
        "ticket_price_history_query",
        "fallback",
    ],
    "weather_today": ["baidu_weather_mcp", "openmeteo_mcp", "weather_mcp", "weather"],
    "today_weather": ["baidu_weather_mcp", "openmeteo_mcp", "weather_mcp", "weather"],
    "weather": ["baidu_weather_mcp", "openmeteo_mcp", "weather_mcp", "weather"],
    "forecast": ["baidu_weather_mcp", "openmeteo_mcp", "weather_mcp", "weather"],
    "current_crowd": ["search_mcp", "browser_mcp", "osm_mcp", "places_mcp", "reviews", "fallback"],
    "queue_time": ["search_mcp", "browser_mcp", "osm_mcp", "places_mcp", "reviews", "fallback"],
    "crowd_level": ["search_mcp", "browser_mcp", "osm_mcp", "places_mcp", "reviews", "fallback"],
    "nearby_food": [
        "baidu_place_search_mcp",
        "baidu_place_detail_mcp",
        "baidu_reverse_geocode_mcp",
        "baidu_ip_location_mcp",
        "osm_mcp",
        "places_mcp",
        "search_mcp",
        "restaurant",
        "fallback",
    ],
    "nearby_rest_area": [
        "baidu_place_search_mcp",
        "baidu_place_detail_mcp",
        "baidu_reverse_geocode_mcp",
        "baidu_ip_location_mcp",
        "osm_mcp",
        "places_mcp",
        "search_mcp",
        "restaurant",
        "fallback",
    ],
    "entity_resolution": [
        "baidu_place_search_mcp",
        "baidu_place_detail_mcp",
        "baidu_geocode_mcp",
        "baidu_reverse_geocode_mcp",
        "search_mcp",
        "osm_mcp",
        "wikidata_mcp",
        "wikipedia_mcp",
        "fallback",
    ],
    "public_web_search": ["search_mcp", "browser_mcp", "fallback"],
    "official_page_read": ["official_page_reader_mcp", "browser_mcp", "official", "fallback"],
    "general_travel_advice": [
        "search_mcp",
        "wikipedia_mcp",
        "wikidata_mcp",
        "osm_mcp",
        "places_mcp",
        "places",
        "reviews",
        "transit",
        "knowledge_prior",
        "fallback",
    ],
    "fallback_web_lookup": ["search_mcp", "browser_mcp", "wikipedia_mcp", "fallback", "knowledge_prior"],
    "route_plan": [
        "baidu_route_mcp",
        "baidu_route_matrix_mcp",
        "baidu_traffic_mcp",
        "baidu_geocode_mcp",
        "baidu_place_search_mcp",
        "transit",
        "fallback",
    ],
    "transport_planning": [
        "baidu_route_mcp",
        "baidu_route_matrix_mcp",
        "baidu_traffic_mcp",
        "baidu_geocode_mcp",
        "transit",
        "fallback",
    ],
    "road_traffic": ["baidu_traffic_mcp", "baidu_route_mcp", "search_mcp", "fallback"],
    "traffic_status": ["baidu_traffic_mcp", "baidu_route_mcp", "search_mcp", "fallback"],
    "congestion_risk": ["baidu_traffic_mcp", "search_mcp", "fallback"],
    "self_drive_risk": ["baidu_traffic_mcp", "baidu_route_mcp", "search_mcp", "fallback"],
    "user_location": ["baidu_ip_location_mcp", "baidu_reverse_geocode_mcp"],
    "nearby_me": ["baidu_ip_location_mcp", "baidu_place_search_mcp", "baidu_reverse_geocode_mcp"],
    "seasonal_operation_status": [
        "search_mcp",
        "official_source_discovery_mcp",
        "baidu_place_search_mcp",
        "baidu_place_detail_mcp",
        "baidu_geocode_mcp",
        "official_page_reader_mcp",
        "browser_mcp",
    ],
}
